AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template SAM para desplegar una aplicación React.js en S3 y CloudFront con seguridad.



Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-react-app-bucket-${stage}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  ReactAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: AllowCloudFrontAccess
          Effect: Allow
          Principal:
            CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
          Action: "s3:GetObject"
          Resource: !Sub "${ReactAppBucket.Arn}/*"
        - Sid: DenyPublicAccess
          Effect: Deny
          Principal: "*"
          Action: "s3:GetObject"
          Resource: !Sub "${ReactAppBucket.Arn}/*"
          Condition:
            Bool:
              aws:SecureTransport: "false"

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "Access Identity for ${AWS::StackName}"

  ReactAppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
        - Id: ReactAppOrigin
          DomainName: !GetAtt ReactAppBucket.DomainName
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: ReactAppOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100
        CustomErrorResponses:
        - ErrorCode: 404
          ResponsePagePath: /index.html
          ResponseCode: 200
          ErrorCachingMinTTL: 300
Parameters:
  stage:
    Type: String
    Default: DEV
Outputs:
  ReactAppBucketName:
    Description: "S3 Bucket where the React app is hosted"
    Value: !Ref ReactAppBucket

  ReactAppCloudFrontDistribution:
    Description: "CloudFront distribution URL"
    Value: !GetAtt ReactAppDistribution.DomainName
